import type { Wedding } from '@/lib/db/schema'

/** A full `wedding` row with every optional field null, to override per test. */
export function weddingRow(overrides: Partial<Wedding> = {}): Wedding {
  const base = {
    id: 1,
    coupleNames: '',
    eventDate: null,
    eventTime: null,
    venue: null,
    message: null,
    mapUrl: null,
    schedule: null,
    dressCode: null,
    accommodation: null,
    transport: null,
    giftMessage: null,
    giftDetails: null,
    privacyContact: null,
    totalBudgetCents: 0,
    venueAddress: null,
    venuePhone: null,
    venueCoordinator: null,
    ceremonyStart: null,
    ceremonyEnd: null,
    receptionStart: null,
    receptionEnd: null,
    monogram: null,
    hashtag: null,
    city: null,
    tagline: null,
    story: null,
    quoteText: null,
    quoteAttribution: null,
    brideParents: null,
    groomParents: null,
    dressCodeNote: null,
    guestNotes: null,
    receptionPlace: null,
    receptionAddress: null,
    receptionMapUrl: null,
    giftEnvelopeNote: null,
    giftAccounts: null,
    contactWhatsapp: null,
    coupleImageUrl: null,
    musicTitle: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  } satisfies Wedding
  return { ...base, ...overrides }
}
